# Generated by Django 2.1.5 on 2019-01-31 00:23

from django.db import migrations, models
import django.db.models.deletion
import project.crs.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_first_name', models.CharField(max_length=200)),
                ('booking_last_name', models.CharField(max_length=200)),
                ('booking_email', models.CharField(max_length=200)),
                ('booking_phone', models.CharField(max_length=200)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('number_of_adults', models.IntegerField(validators=[project.crs.models.number_of_adults_valid])),
                ('number_of_children', models.IntegerField()),
                ('number_of_infants', models.IntegerField()),
                ('number_of_nights', models.IntegerField(validators=[project.crs.models.number_of_nights_valid])),
                ('check_in', models.DateField(validators=[project.crs.models.check_in_valid])),
                ('state', models.CharField(choices=[('PE', 'pending'), ('CO', 'confirmed'), ('CA', 'cancelled')], default='PE', editable=False, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='crs.Property')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='crs.RoomType'),
        ),
    ]
